Repository babel/ember-cli-babel, pull requests merged in 2019-02, with the labels that each got.

#266 Update to broccoli-babel-transpiler@7.1.2.
  node-tests/utils/terminate-workers.js
  package.json
  yarn.lock
Labels: bug

#267 Ensure external helpers are not used when modules are not transpiled.
  index.js
  node-tests/addon-test.js
Labels: bug

#268 Update babel-plugin-debug-macros
  package.json
  yarn.lock
Labels: internal

#270 Update Ember modules API to include @glimmer/tracked.
  package.json
  yarn.lock
Labels: enhancement
