Repository babel/ember-cli-babel, pull requests merged in 2022-10, with the labels that each got.

#452 Move `@babel/core` to `peerDependencies` to resolve peer dependency warnings and errors
  package.json
Labels: bug, breaking

#454 Drop support for Node < v14 and add support for Node v16 and v18
  .github/workflows/ci.yml
  package.json
  yarn.lock
Labels: enhancement, breaking

#458 Drop support for the `includePolyfill` option
  README.md
  ember-cli-build.js
  index.js
  node-tests/addon-test.js
  package.json
  tests/dummy/app/app.js
  yarn.lock
Labels: breaking

#460 Update `broccoli-babel-transpiler` to v8.0.0-beta.1
  index.js
  node-tests/addon-test.js
  package.json
  yarn.lock
Labels: breaking
