Repository babel/ember-cli-babel, pull requests merged in 2023-08, with the labels that each got.

#493 Drop support for Node v14 and add support for Node v20
  .github/workflows/ci.yml
  package.json
Labels: enhancement, breaking

#492 Update `babel-plugin-module-resolver`
  package.json
  yarn.lock
Labels: enhancement, dependencies

#494 Update `broccoli-babel-transpiler` to v8
  package.json
  yarn.lock
Labels: breaking, dependencies

#467 Clarify how to set `enableTypeScriptTransform` in Ember apps, addons and engines
  README.md
Labels: documentation

#496 Update development dependencies
  .eslintignore
  .eslintrc.js
  .gitignore
  node-tests/addon-test.js
  package.json
  tests/dummy/app/app.js
  tests/dummy/app/controllers/application.js
  tests/dummy/app/router.js
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  yarn.lock
Labels: dependencies
